development: &pg
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: sample_app_user
  password: password

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: sample_app_user
  password: password

production:
  <<: *pg

cucumber:
  <<: *test
