development:
  adapter: postgresql
  encoding: unicode
  database: coba
  pool: 5
  username: coba
  password: password

test: &test
  adapter: postgresql
  encoding: unicode
  database: coba
  pool: 5
  username: coba
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: coba
  pool: 5
  username: coba
  password: password

cucumber:
  <<: *test